- name: Create modules load file for containerd
  ansible.builtin.copy:
    dest: /etc/modules-load.d/containerd.conf
    content: |
      overlay
      br_netfilter
    mode: '0644'

- name: Load modules
  become: true
  ansible.builtin.modprobe:
    name: "{{ item }}"
  loop: "{{ modprobes }}"

- name: Create sysctl configurations
  ansible.builtin.copy:
    dest: /etc/sysctl.d/99-kubernetes-cri.conf
    content: |
      net.bridge.bridge-nf-call-iptables  = 1
      net.ipv4.ip_forward                 = 1
      net.bridge.bridge-nf-call-ip6tables = 1
    mode: '0644'

- name: Apply sysctl
  become: true
  ansible.builtin.command: sysctl --system

- name: Install dependencies for containerd
  become: true
  ansible.builtin.apt:
    update_cache: yes
    name: "{{ item }}"
    state: present
  loop: "{{ dependencies }}"

- name: Create apt keyring directory
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Download Docker GPG key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /tmp/docker.gpg
    mode: '0644'


- name: Install Docker apt keyring
  become: true
  ansible.builtin.command:
    cmd: gpg --dearmor -o /etc/apt/keyrings/docker.gpg /tmp/docker.gpg
  args:
    creates: /etc/apt/keyrings/docker.gpg

- name: Adicionar repositório Docker
  ansible.builtin.apt_repository:
    repo: >-
      deb [arch={{ ansible_architecture }} signed-by=/etc/apt/keyrings/docker.gpg]
      https://download.docker.com/linux/ubuntu
      {{ ansible_distribution_release }} stable
    filename: docker
    state: present

- name: Atualizar cache do apt
  become: true
  ansible.builtin.apt:
    update_cache: yes

- name: Install containerd
  become: true
  ansible.builtin.apt:
    update_cache: yes
    name: containerd
    state: present

- name: Criar config padrão do containerd
  ansible.builtin.command:
    cmd: containerd config default
  register: containerd_default_config

- name: Criar diretório /etc/containerd
  ansible.builtin.file:
    path: /etc/containerd
    state: directory
    mode: '0755'

- name: Gravar config em /etc/containerd/config.toml
  ansible.builtin.copy:
    dest: /etc/containerd/config.toml
    content: "{{ containerd_default_config.stdout }}"
    mode: "0644"

- name: Ativar SystemdCgroup no containerd
  ansible.builtin.replace:
    path: /etc/containerd/config.toml
    regexp: 'SystemdCgroup = false'
    replace: 'SystemdCgroup = true'

- name: Atualizar sandbox_image para pause:3.10
  ansible.builtin.replace:
    path: /etc/containerd/config.toml
    regexp: 'sandbox_image = ".*"'
    replace: 'sandbox_image = "registry.k8s.io/pause:3.10"'

- name: Reiniciar containerd
  ansible.builtin.service:
    name: containerd
    state: restarted
